cluster.name: nexus-local
node.name: nexus-node-1

path.data: ./data/elasticsearch
path.logs: ./logs

network.host: 127.0.0.1
http.port: 9200

discovery.type: single-node
xpack.security.enabled: false
