filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./logs/*.log
    fields_under_root: true
    fields:
      stack: nexus

output.elasticsearch:
  hosts: ["http://127.0.0.1:9200"]

setup.kibana:
  host: "http://127.0.0.1:5601"
